import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from 'next/image';
import Navigation from "./components/Navigation";
import { mainNavigation } from "./pages";
import UserStatus from "./components/UserStatus";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="flex flex-row ">
          <a href="/">
            <Image 
              src="/imgs/KoncernLogga.png" 
              alt="Koncern Logga" 
              width={50} 
              height={50}
            />
          </a>
          <Navigation pages={mainNavigation}/>
          <UserStatus/>
        </header>
        <main>{children}</main>
        <footer className="flex flex-row gap-2">
          <div>
            <a href="https://facebook.se" className="icon-link"><i></i>face</a>
          </div>
        </footer>
      </body>
    </html>
  );
}
